# Generated by Django 2.0.6 on 2018-06-05 10:09

from django.db import migrations, models
import painless.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlovakiAwardsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='CMq5bOF2BZs', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('name', models.CharField(max_length=128)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='SlovakiNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='Vx_yJblcTG8', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-submit_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SlovakiNewsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'News Group',
                'verbose_name_plural': 'News Groups',
            },
        ),
        migrations.CreateModel(
            name='SlovakiNewsMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='u2jDP4-SSvU', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('movie_name', models.CharField(max_length=128)),
                ('movie', models.FileField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'News Movie',
                'verbose_name_plural': 'News Movies',
            },
        ),
        migrations.CreateModel(
            name='SlovakiNewsPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='S2Cn4fLmXvQ', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('photo_name', models.CharField(max_length=128)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'News Photo',
                'verbose_name_plural': 'News Photos',
            },
        ),
        migrations.CreateModel(
            name='SlovakiNewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'News Tag',
                'verbose_name_plural': 'News Tags',
                'ordering': ('tag_name',),
            },
        ),
        migrations.CreateModel(
            name='SlovakiProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='5S_gTouZsqk', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(help_text='Max Length of this field is 2048 characters.', max_length=2048)),
                ('description', models.TextField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'ordering': ('-submit_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SlovakiProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='SlovakiProductMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='QTtPFtufbPo', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('movie_name', models.CharField(max_length=128)),
                ('movie', models.FileField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'Product Movie',
                'verbose_name_plural': 'Product Movies',
            },
        ),
        migrations.CreateModel(
            name='SlovakiProductPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='zjZJ2M6oWPc', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('photo_name', models.CharField(max_length=128)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
            },
        ),
        migrations.CreateModel(
            name='SlovakiProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'ordering': ('tag_name',),
            },
        ),
        migrations.CreateModel(
            name='SlovakiWebsiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('title1', models.CharField(max_length=16)),
                ('title2', models.CharField(max_length=16)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('quality1', models.CharField(max_length=128)),
                ('quality2', models.CharField(max_length=128)),
                ('quality3', models.CharField(max_length=128)),
                ('summary_feature', models.TextField()),
                ('description_feature', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='slovakiproduct',
            name='groups',
            field=models.ManyToManyField(to='slovaki.SlovakiProductGroup'),
        ),
        migrations.AddField(
            model_name='slovakiproduct',
            name='movies',
            field=models.ManyToManyField(to='slovaki.SlovakiProductMovies'),
        ),
        migrations.AddField(
            model_name='slovakiproduct',
            name='photos',
            field=models.ManyToManyField(to='slovaki.SlovakiProductPhotos'),
        ),
        migrations.AddField(
            model_name='slovakiproduct',
            name='tags',
            field=models.ManyToManyField(to='slovaki.SlovakiProductTags'),
        ),
        migrations.AddField(
            model_name='slovakinews',
            name='groups',
            field=models.ManyToManyField(to='slovaki.SlovakiNewsGroup'),
        ),
        migrations.AddField(
            model_name='slovakinews',
            name='movies',
            field=models.ManyToManyField(to='slovaki.SlovakiNewsMovies'),
        ),
        migrations.AddField(
            model_name='slovakinews',
            name='photos',
            field=models.ManyToManyField(to='slovaki.SlovakiNewsPhotos'),
        ),
        migrations.AddField(
            model_name='slovakinews',
            name='tags',
            field=models.ManyToManyField(to='slovaki.SlovakiNewsTags'),
        ),
    ]
