# Generated by Django 2.0.6 on 2018-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovaki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slovakiawardscontent',
            name='sku',
            field=models.CharField(default='TcNXAjujzcI', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinews',
            name='sku',
            field=models.CharField(default='-njMIljNYvo', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinewsmovies',
            name='sku',
            field=models.CharField(default='9myWOJdnPY4', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinewsphotos',
            name='sku',
            field=models.CharField(default='y9Ia-VnO9SI', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproduct',
            name='sku',
            field=models.CharField(default='eEcaBAsEbRI', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproductmovies',
            name='sku',
            field=models.CharField(default='HsBB02jjIqw', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproductphotos',
            name='sku',
            field=models.CharField(default='tausSyQUbeI', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
