# Generated by Django 2.0.6 on 2018-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovaki', '0003_auto_20180605_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slovakiawardscontent',
            name='sku',
            field=models.CharField(default='knA0KUnsz6c', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinews',
            name='sku',
            field=models.CharField(default='1D1kz8XCzXs', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinewsmovies',
            name='sku',
            field=models.CharField(default='I2vJKxn_diA', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakinewsphotos',
            name='sku',
            field=models.CharField(default='FDwUIqVVtQc', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproduct',
            name='sku',
            field=models.CharField(default='NjQ1uz4achQ', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproductmovies',
            name='sku',
            field=models.CharField(default='_e2-LgKhb40', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='slovakiproductphotos',
            name='sku',
            field=models.CharField(default='njZHozuasGg', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
