# Generated by Django 2.0.6 on 2018-06-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='dfAL1arLkac', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('title', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=526)),
                ('priority', models.CharField(choices=[('1', 'Low'), ('2', 'Normal'), ('3', 'High'), ('4', 'Urgant')], default=('1', 'Low'), max_length=1)),
                ('status', models.CharField(choices=[('0', 'Closed'), ('1', 'Open')], default=('0', 'Closed'), max_length=1)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', '-status', '-order_date'),
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('file_address', models.CharField(max_length=526, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20, null=True)),
                ('users', models.ManyToManyField(help_text='list of users in a department', to=settings.AUTH_USER_MODEL, verbose_name='users in dept')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=526, null=True)),
                ('request_type', models.CharField(choices=[('202', 'Answered'), ('201', 'Request')], max_length=3, null=True)),
                ('submit_date', models.DateTimeField(auto_now=True)),
                ('attachments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketAttachment')),
                ('submited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Reply Message',
                'verbose_name_plural': 'Ticket Reply Messages',
                'ordering': ('request_type', 'submit_date'),
            },
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='reply_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketReply'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketDepartment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.TicketReply'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='submited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
