# Generated by Django 2.0.6 on 2018-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sku',
            field=models.CharField(default='ZBVoXfoaNyU', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
