# Generated by Django 2.0.6 on 2018-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180605_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sku',
            field=models.CharField(default='tm4oFOxuv68', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
