# Generated by Django 2.0.6 on 2018-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180605_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sku',
            field=models.CharField(default='CHeBNypz4bs', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
