# Generated by Django 2.0.6 on 2018-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardscontent',
            name='sku',
            field=models.CharField(default='URvApFTfq9s', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
