# Generated by Django 2.0.6 on 2018-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180605_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardscontent',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='awardscontent',
            name='sku',
            field=models.CharField(default='VjQZANJCLFY', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
