# Generated by Django 2.0.6 on 2018-06-05 05:45

from django.db import migrations, models
import painless.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='p8OlDWzfOW8', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(help_text='Max Length of this field is 2048 characters.', max_length=2048)),
                ('description', models.TextField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'ordering': ('-submit_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='ProductMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='uGCV4YfoPo0', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('movie_name', models.CharField(max_length=128)),
                ('movie', models.FileField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'Product Movie',
                'verbose_name_plural': 'Product Movies',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='nG9huwL26N4', help_text='Unique code for refrence to supervisors', max_length=15)),
                ('photo_name', models.CharField(max_length=128)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=painless.functions.upload_location)),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'ordering': ('tag_name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(to='product.ProductGroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='movies',
            field=models.ManyToManyField(to='product.ProductMovies'),
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(to='product.ProductPhotos'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product.ProductTags'),
        ),
    ]
