# Generated by Django 2.0.6 on 2018-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='WmpnnuR_3k0', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='sku',
            field=models.CharField(default='TqhgyjlQfEw', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='sku',
            field=models.CharField(default='b5z1bhomRJc', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
