# Generated by Django 2.0.6 on 2018-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180605_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='COPL8rud-f0', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='sku',
            field=models.CharField(default='HZogD4mhXXU', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='sku',
            field=models.CharField(default='b5-OcMnCFYM', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
