# Generated by Django 2.0.6 on 2018-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180605_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='3r8KrT87Bpk', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='sku',
            field=models.CharField(default='DWzCRzx-7Dk', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='sku',
            field=models.CharField(default='szP5AQLsx6A', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
