# Generated by Django 2.0.6 on 2018-06-05 16:35

from django.db import migrations, models
import painless.functions


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180605_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='sNdikFml17w', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to=painless.functions.upload_movie_location),
        ),
        migrations.AlterField(
            model_name='productmovies',
            name='sku',
            field=models.CharField(default='2maYQLqkzDk', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='sku',
            field=models.CharField(default='ckcQG0VDHOQ', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
