# Generated by Django 2.0.6 on 2018-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sku',
            field=models.CharField(default='vxY6mlScUwA', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='newsmovies',
            name='sku',
            field=models.CharField(default='HXFm4TZBuwI', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='newsphotos',
            name='sku',
            field=models.CharField(default='xPBjYllJVBs', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
