# Generated by Django 2.0.6 on 2018-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180605_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sku',
            field=models.CharField(default='ec-OlPrcmfU', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='newsmovies',
            name='sku',
            field=models.CharField(default='iPYMbtgQAyE', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
        migrations.AlterField(
            model_name='newsphotos',
            name='sku',
            field=models.CharField(default='PxOv3oDrkCE', help_text='Unique code for refrence to supervisors', max_length=15),
        ),
    ]
